SELECT STRING_AGG(
           CONCAT(COMPOSITE_ID, ',', RECALC_ID),
           ','
       ) AS RECALC_STG_ACCT
FROM
(
    SELECT DISTINCT
           STG.COMPOSITE_ID,
           STG.RECALC_ID
    FROM MIO_LOAD..SSO_CALCULATED_ACCOUNTING_DATA_STAGE AS STG
) AS D;

Example result:

1001,5001,1002,5002,1003,5003

If you only need one combined value per row, use:

SELECT DISTINCT
       CONCAT(STG.COMPOSITE_ID, ',', STG.RECALC_ID) AS RECALC_STG_ACCT
FROM MIO_LOAD..SSO_CALCULATED_ACCOUNTING_DATA_STAGE AS STG;
